import type { Config } from 'tailwindcss';
import defaultTheme from 'tailwindcss/defaultTheme';

export default {
    content: [
        './resources/views/**/*.blade.php',
        './resources/js/**/*.{ts,tsx}',
    ],
    theme: {
        extend: {
            fontFamily: {
                display: ['Lexend', ...defaultTheme.fontFamily.sans],
                body: ['Manrope', ...defaultTheme.fontFamily.sans],
                sans: ['Manrope', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'display-md': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
            },
            colors: {
                surface: '#f9f9f9',
                'surface-dim': '#dadada',
                'surface-bright': '#f9f9f9',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f3f3f4',
                'surface-container': '#eeeeee',
                'surface-container-high': '#e8e8e8',
                'surface-container-highest': '#e2e2e2',
                primary: '#004ac6',
                'primary-container': '#2563eb',
                'on-primary': '#ffffff',
                'on-primary-container': '#eeefff',
                'primary-fixed': '#dbe1ff',
                'primary-fixed-dim': '#b4c5ff',
                secondary: '#576065',
                'secondary-container': '#dbe4ea',
                'on-secondary': '#ffffff',
                'on-secondary-container': '#5d666b',
                tertiary: '#4d556b',
                'tertiary-container': '#656d84',
                'on-surface': '#1a1c1c',
                'on-surface-variant': '#434655',
                outline: '#737686',
                'outline-variant': '#c3c6d7',
                error: '#ba1a1a',
                'error-container': '#ffdad6',
                'inverse-surface': '#2f3131',
                'inverse-on-surface': '#f0f1f1',
                'inverse-primary': '#b4c5ff',
                success: '#10b981',
                warning: '#f59e0b',
            },
            spacing: {
                'xs-': '4px',
                'sm-': '12px',
                'md-': '24px',
                'lg-': '40px',
                'xl-': '64px',
            },
            borderRadius: {
                sm: '0.25rem',
                DEFAULT: '0.5rem',
                md: '0.75rem',
                lg: '1rem',
                xl: '1.5rem',
                full: '9999px',
            },
            boxShadow: {
                'glass-sm': '0 4px 16px rgba(37, 99, 235, 0.05)',
                glass: '0 8px 30px rgba(37, 99, 235, 0.05)',
                'glass-lg': '0 12px 40px rgba(37, 99, 235, 0.06)',
                glow: '0 8px 24px rgba(37, 99, 235, 0.35)',
                'inner-soft': 'inset 0 1px 2px rgba(0, 0, 0, 0.04)',
            },
            backgroundImage: {
                'serene-gradient': 'linear-gradient(135deg, #f9f9f9 0%, #eef2ff 100%)',
            },
        },
    },
    plugins: [],
} satisfies Config;
